# ali
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/ali.1.gz
complete -c ali -o list --description 'switch is specified, and an address expands to multiple addresses, each addre…'
complete -c ali -o user --description 'switch directs ali to perform its processing in an inverted fashion: instead …'
complete -c ali -o alias --description 'aliasfile switch will be read.'
complete -c ali -o nolist --description '.'
complete -c ali -o nouser --description '.'

