# anno
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/anno.1.gz
complete -c anno -o component --description 'switch specifies the field name, and the.'
complete -c anno -o text --description 'switch specifies the field body.'
complete -c anno -o draft --description 'switch.'
complete -c anno -o anno --description 'switch.'
complete -c anno -o nodate --description 'switch inhibits the date annotation, leaving only the body annotation.'
complete -c anno -o append --description 'switch is specified.'
complete -c anno -o noinplace --description 'switch.'
complete -c anno -o list --description 'switch produces a listing of the field bodies for header fields with names ma…'
complete -c anno -o number --description 'switch is also used.  A tab character separates the number and the field body.'
complete -c anno -o delete --description 'switch removes header fields from messages.'
complete -c anno -o preserve --description 'switch is used.  A matching.'
complete -c anno -o nopreserve --description 'switch allows time preservation to be turned off, if enabled in the profile.'
complete -c anno -o inplace --description '.'
complete -c anno -o date --description '.'

