# ap
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man8/ap.8.gz
complete -c ap -o format --description 'string or.'
complete -c ap -o width --description 'The width of the terminal.'

