# aria_s3_copy
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/aria_s3_copy.1.gz
complete -c aria_s3_copy -s '?' -s h -l help --description 'Display help and exit.'
complete -c aria_s3_copy -s k -l s3-access-key --description 'AWS access key ID.'
complete -c aria_s3_copy -s r -o s3-region --description 'AWS region.'
complete -c aria_s3_copy -s K -o s3-secret-key --description 'AWS secret access key ID.'
complete -c aria_s3_copy -s b -o s3-bucket --description 'AWS prefix for tables.'
complete -c aria_s3_copy -o s3-host-name --description 'Host name to S3 provider.'
complete -c aria_s3_copy -s c -o compress --description 'Use compression.'
complete -c aria_s3_copy -s o -o op --description 'Operation to execute.  One of \'from_s3\', \'to_s3\' or \'delete_from_s3\'.'
complete -c aria_s3_copy -s d -o database --description 'Database for copied table (second prefix).'
complete -c aria_s3_copy -s B -o s3-block-size --description 'Block size for data/index blocks in s3.'
complete -c aria_s3_copy -s L -o s3-protocol-version --description 'Protocol used to communication with S3.'
complete -c aria_s3_copy -s f -o force --description 'Force copy even if target exists.'
complete -c aria_s3_copy -s V -o version --description 'Print version and exit.'
complete -c aria_s3_copy -l s3-debug --description 'Output debug log from marias3 to stdout.'
complete -c aria_s3_copy -s v -l verbose --description 'Be verbose.'

