# bundle-remove
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/bundle-remove.1.gz
complete -c bundle-remove -l install --description 'Runs bundle install after the given gems have been removed from the Gemfile, …'

