# bundle-init
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/bundle-init.1.gz
complete -c bundle-init -l gemspec --description 'Use the specified . gemspec to create the [Gemfile(5)][Gemfile(5)].'

