# bundle-clean
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/bundle-clean.1.gz
complete -c bundle-clean -l dry-run --description 'Print the changes, but do not clean the unused gems.'

