# bundle-exec
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/bundle-exec.1.gz
complete -c bundle-exec -l keep-file-descriptors --description 'Exec in Ruby 2. 0 began discarding non-standard file descriptors.'

