# burst
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/burst.1.gz
complete -c burst -o inplace --description 'is given, each digest is replaced by its table of contents and the digest is …'
complete -c burst -o noinplace --description 'is given, each digest is preserved, no table of contents is produced, and the…'
complete -c burst -o automime --description 'is given, burst will try to determine if the message is formatted with MIME a…'
complete -c burst -o mime --description 'switch can be used to enforce the use of MIME formatting.   The.'
complete -c burst -o nomime --description 'switch will force burst to use RFC 934 rules.'
complete -c burst -o quiet --description 'switch directs burst to be silent about reporting messages that are not in di…'
complete -c burst -o verbose --description 'switch directs burst to tell the user the general actions that it is taking t…'
complete -c burst -o noquiet --description '.'
complete -c burst -o noverbose --description '.'

