# crontab
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/crontab.1.gz
complete -c crontab -s l --description 'Displays the current crontab on standard output.'
complete -c crontab -s r --description 'Removes the current crontab.'
complete -c crontab -s e --description 'Edits the current crontab using the editor specified by the  VISUAL or  EDITO…'
complete -c crontab -s i --description 'This option modifies the  "-r" option to prompt the user for a \'y/Y\' response…'
complete -c crontab -s s --description 'Appends the current SELinux security context string as an MLS_LEVEL setting t…'

