# dp
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man8/dp.8.gz
complete -c dp -o format --description 'string or.'
complete -c dp -o width --description 'The width of the terminal.'

