# dvispc
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/dvispc.1.gz
complete -c dvispc -s t --description 'option.  Also, dvispc -x can accept DTL-compatible text input.'

