# dvitomp
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/dvitomp.1.gz
complete -c dvitomp -o help --description 'write usage summary and exit.'
complete -c dvitomp -o version --description 'output version information and exit.'

