# flist
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/flist.1.gz
complete -c flist -o sequence --description 'switch specifies the sequence to which messages should belong.'
complete -c flist -o noshowzero --description 'will cause flist to print only those folder/sequence combinations where the f…'
complete -c flist -o recurse --description 'is given, then for each folder that is searched, flist will also recursively …'
complete -c flist -o fast --description 'is given, only the names of the folders searched will be displayed, and flist…'
complete -c flist -o all --description 'switch is given (and no folders are specified with +folder ), then flist will…'
complete -c flist -o alpha --description 'or in a priority order defined by the  Flist-Order  profile entry (with.'
complete -c flist -o noalpha --description 'Each item in the  Flist-Order  is a folder name or a folder name pattern that…'
complete -c flist -o showzero --description '.'
complete -c flist -o noall --description '.'
complete -c flist -o norecurse --description '.'
complete -c flist -o nofast --description '.'

