# fmtdump
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man8/fmtdump.8.gz
complete -c fmtdump -o format --description 'string and.'
complete -c fmtdump -o form --description 'formatfile switches may be used to specify a format string or format file to …'

