# hugo-mod-verify
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/hugo-mod-verify.1.gz
complete -c hugo-mod-verify -l clean --description '	delete module cache for dependencies that fail verification.'
complete -c hugo-mod-verify -s h -l help --description '	help for verify OPTIONS INHERITED FROM PARENT COMMANDS.'
complete -c hugo-mod-verify -l config --description '	config file (default is path/config. yaml|json|toml).'
complete -c hugo-mod-verify -l configDir --description '	config dir.'
complete -c hugo-mod-verify -l debug --description '	debug output.'
complete -c hugo-mod-verify -s e -l environment --description '	build environment.'
complete -c hugo-mod-verify -l ignoreVendor --description '	ignores any _vendor directory.'
complete -c hugo-mod-verify -l ignoreVendorPaths --description '	ignores any _vendor for module paths matching the given Glob pattern.'
complete -c hugo-mod-verify -l log --description '	enable Logging.'
complete -c hugo-mod-verify -l logFile --description '	log File path (if set, logging enabled automatically).'
complete -c hugo-mod-verify -l quiet --description '	build in quiet mode.'
complete -c hugo-mod-verify -s s -l source --description '	filesystem path to read files relative from.'
complete -c hugo-mod-verify -l themesDir --description '	filesystem path to themes directory.'
complete -c hugo-mod-verify -s v -l verbose --description '	verbose output.'
complete -c hugo-mod-verify -l verboseLog --description '	verbose logging SEE ALSO.'

