# hugo-new-site
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/hugo-new-site.1.gz
complete -c hugo-new-site -l force --description '	init inside non-empty directory.'
complete -c hugo-new-site -s f -l format --description '	config  frontmatter format.'
complete -c hugo-new-site -s h -l help --description '	help for site OPTIONS INHERITED FROM PARENT COMMANDS.'
complete -c hugo-new-site -l config --description '	config file (default is path/config. yaml|json|toml).'
complete -c hugo-new-site -l configDir --description '	config dir.'
complete -c hugo-new-site -l debug --description '	debug output.'
complete -c hugo-new-site -s e -l environment --description '	build environment.'
complete -c hugo-new-site -l ignoreVendor --description '	ignores any _vendor directory.'
complete -c hugo-new-site -l ignoreVendorPaths --description '	ignores any _vendor for module paths matching the given Glob pattern.'
complete -c hugo-new-site -l log --description '	enable Logging.'
complete -c hugo-new-site -l logFile --description '	log File path (if set, logging enabled automatically).'
complete -c hugo-new-site -l quiet --description '	build in quiet mode.'
complete -c hugo-new-site -s s -l source --description '	filesystem path to read files relative from.'
complete -c hugo-new-site -l themesDir --description '	filesystem path to themes directory.'
complete -c hugo-new-site -s v -l verbose --description '	verbose output.'
complete -c hugo-new-site -l verboseLog --description '	verbose logging SEE ALSO.'

