# hugo-config
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/hugo-config.1.gz
complete -c hugo-config -s h -l help --description '	help for config OPTIONS INHERITED FROM PARENT COMMANDS.'
complete -c hugo-config -l config --description '	config file (default is path/config. yaml|json|toml).'
complete -c hugo-config -l configDir --description '	config dir.'
complete -c hugo-config -l debug --description '	debug output.'
complete -c hugo-config -s e -l environment --description '	build environment.'
complete -c hugo-config -l ignoreVendor --description '	ignores any _vendor directory.'
complete -c hugo-config -l ignoreVendorPaths --description '	ignores any _vendor for module paths matching the given Glob pattern.'
complete -c hugo-config -l log --description '	enable Logging.'
complete -c hugo-config -l logFile --description '	log File path (if set, logging enabled automatically).'
complete -c hugo-config -l quiet --description '	build in quiet mode.'
complete -c hugo-config -s s -l source --description '	filesystem path to read files relative from.'
complete -c hugo-config -l themesDir --description '	filesystem path to themes directory.'
complete -c hugo-config -s v -l verbose --description '	verbose output.'
complete -c hugo-config -l verboseLog --description '	verbose logging SEE ALSO.'

