# hugo-gen
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/hugo-gen.1.gz
complete -c hugo-gen -s h -l help --description '	help for gen OPTIONS INHERITED FROM PARENT COMMANDS.'
complete -c hugo-gen -l config --description '	config file (default is path/config. yaml|json|toml).'
complete -c hugo-gen -l configDir --description '	config dir.'
complete -c hugo-gen -l debug --description '	debug output.'
complete -c hugo-gen -s e -l environment --description '	build environment.'
complete -c hugo-gen -l ignoreVendor --description '	ignores any _vendor directory.'
complete -c hugo-gen -l ignoreVendorPaths --description '	ignores any _vendor for module paths matching the given Glob pattern.'
complete -c hugo-gen -l log --description '	enable Logging.'
complete -c hugo-gen -l logFile --description '	log File path (if set, logging enabled automatically).'
complete -c hugo-gen -l quiet --description '	build in quiet mode.'
complete -c hugo-gen -s s -l source --description '	filesystem path to read files relative from.'
complete -c hugo-gen -l themesDir --description '	filesystem path to themes directory.'
complete -c hugo-gen -s v -l verbose --description '	verbose output.'
complete -c hugo-gen -l verboseLog --description '	verbose logging SEE ALSO.'

