# hugo-list-drafts
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/hugo-list-drafts.1.gz
complete -c hugo-list-drafts -s h -l help --description '	help for drafts OPTIONS INHERITED FROM PARENT COMMANDS.'
complete -c hugo-list-drafts -l config --description '	config file (default is path/config. yaml|json|toml).'
complete -c hugo-list-drafts -l configDir --description '	config dir.'
complete -c hugo-list-drafts -l debug --description '	debug output.'
complete -c hugo-list-drafts -s e -l environment --description '	build environment.'
complete -c hugo-list-drafts -l ignoreVendor --description '	ignores any _vendor directory.'
complete -c hugo-list-drafts -l ignoreVendorPaths --description '	ignores any _vendor for module paths matching the given Glob pattern.'
complete -c hugo-list-drafts -l log --description '	enable Logging.'
complete -c hugo-list-drafts -l logFile --description '	log File path (if set, logging enabled automatically).'
complete -c hugo-list-drafts -l quiet --description '	build in quiet mode.'
complete -c hugo-list-drafts -s s -l source --description '	filesystem path to read files relative from.'
complete -c hugo-list-drafts -l themesDir --description '	filesystem path to themes directory.'
complete -c hugo-list-drafts -s v -l verbose --description '	verbose output.'
complete -c hugo-list-drafts -l verboseLog --description '	verbose logging SEE ALSO.'

