# hugo-mod-clean
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/hugo-mod-clean.1.gz
complete -c hugo-mod-clean -l all --description '	clean entire module cache.'
complete -c hugo-mod-clean -s h -l help --description '	help for clean.'
complete -c hugo-mod-clean -l pattern --description '	pattern matching module paths to clean (all if not set), e. g.'
complete -c hugo-mod-clean -l config --description '	config file (default is path/config. yaml|json|toml).'
complete -c hugo-mod-clean -l configDir --description '	config dir.'
complete -c hugo-mod-clean -l debug --description '	debug output.'
complete -c hugo-mod-clean -s e -l environment --description '	build environment.'
complete -c hugo-mod-clean -l ignoreVendor --description '	ignores any _vendor directory.'
complete -c hugo-mod-clean -l ignoreVendorPaths --description '	ignores any _vendor for module paths matching the given Glob pattern.'
complete -c hugo-mod-clean -l log --description '	enable Logging.'
complete -c hugo-mod-clean -l logFile --description '	log File path (if set, logging enabled automatically).'
complete -c hugo-mod-clean -l quiet --description '	build in quiet mode.'
complete -c hugo-mod-clean -s s -l source --description '	filesystem path to read files relative from.'
complete -c hugo-mod-clean -l themesDir --description '	filesystem path to themes directory.'
complete -c hugo-mod-clean -s v -l verbose --description '	verbose output.'
complete -c hugo-mod-clean -l verboseLog --description '	verbose logging SEE ALSO.'

