# hugo-env
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/hugo-env.1.gz
complete -c hugo-env -s h -l help --description '	help for env OPTIONS INHERITED FROM PARENT COMMANDS.'
complete -c hugo-env -l config --description '	config file (default is path/config. yaml|json|toml).'
complete -c hugo-env -l configDir --description '	config dir.'
complete -c hugo-env -l debug --description '	debug output.'
complete -c hugo-env -s e -l environment --description '	build environment.'
complete -c hugo-env -l ignoreVendor --description '	ignores any _vendor directory.'
complete -c hugo-env -l ignoreVendorPaths --description '	ignores any _vendor for module paths matching the given Glob pattern.'
complete -c hugo-env -l log --description '	enable Logging.'
complete -c hugo-env -l logFile --description '	log File path (if set, logging enabled automatically).'
complete -c hugo-env -l quiet --description '	build in quiet mode.'
complete -c hugo-env -s s -l source --description '	filesystem path to read files relative from.'
complete -c hugo-env -l themesDir --description '	filesystem path to themes directory.'
complete -c hugo-env -s v -l verbose --description '	verbose output.'
complete -c hugo-env -l verboseLog --description '	verbose logging SEE ALSO.'

