# hugo-mod-tidy
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/hugo-mod-tidy.1.gz
complete -c hugo-mod-tidy -s h -l help --description '	help for tidy OPTIONS INHERITED FROM PARENT COMMANDS.'
complete -c hugo-mod-tidy -l config --description '	config file (default is path/config. yaml|json|toml).'
complete -c hugo-mod-tidy -l configDir --description '	config dir.'
complete -c hugo-mod-tidy -l debug --description '	debug output.'
complete -c hugo-mod-tidy -s e -l environment --description '	build environment.'
complete -c hugo-mod-tidy -l ignoreVendor --description '	ignores any _vendor directory.'
complete -c hugo-mod-tidy -l ignoreVendorPaths --description '	ignores any _vendor for module paths matching the given Glob pattern.'
complete -c hugo-mod-tidy -l log --description '	enable Logging.'
complete -c hugo-mod-tidy -l logFile --description '	log File path (if set, logging enabled automatically).'
complete -c hugo-mod-tidy -l quiet --description '	build in quiet mode.'
complete -c hugo-mod-tidy -s s -l source --description '	filesystem path to read files relative from.'
complete -c hugo-mod-tidy -l themesDir --description '	filesystem path to themes directory.'
complete -c hugo-mod-tidy -s v -l verbose --description '	verbose output.'
complete -c hugo-mod-tidy -l verboseLog --description '	verbose logging SEE ALSO.'

