# hugo-gen-man
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/hugo-gen-man.1.gz
complete -c hugo-gen-man -l dir --description '	the directory to write the man pages.'
complete -c hugo-gen-man -s h -l help --description '	help for man OPTIONS INHERITED FROM PARENT COMMANDS.'
complete -c hugo-gen-man -l config --description '	config file (default is path/config. yaml|json|toml).'
complete -c hugo-gen-man -l configDir --description '	config dir.'
complete -c hugo-gen-man -l debug --description '	debug output.'
complete -c hugo-gen-man -s e -l environment --description '	build environment.'
complete -c hugo-gen-man -l ignoreVendor --description '	ignores any _vendor directory.'
complete -c hugo-gen-man -l ignoreVendorPaths --description '	ignores any _vendor for module paths matching the given Glob pattern.'
complete -c hugo-gen-man -l log --description '	enable Logging.'
complete -c hugo-gen-man -l logFile --description '	log File path (if set, logging enabled automatically).'
complete -c hugo-gen-man -l quiet --description '	build in quiet mode.'
complete -c hugo-gen-man -s s -l source --description '	filesystem path to read files relative from.'
complete -c hugo-gen-man -l themesDir --description '	filesystem path to themes directory.'
complete -c hugo-gen-man -s v -l verbose --description '	verbose output.'
complete -c hugo-gen-man -l verboseLog --description '	verbose logging SEE ALSO.'

