# hugo-gen-doc
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/hugo-gen-doc.1.gz
complete -c hugo-gen-doc -l dir --description '	the directory to write the doc.'
complete -c hugo-gen-doc -s h -l help --description '	help for doc OPTIONS INHERITED FROM PARENT COMMANDS.'
complete -c hugo-gen-doc -l config --description '	config file (default is path/config. yaml|json|toml).'
complete -c hugo-gen-doc -l configDir --description '	config dir.'
complete -c hugo-gen-doc -l debug --description '	debug output.'
complete -c hugo-gen-doc -s e -l environment --description '	build environment.'
complete -c hugo-gen-doc -l ignoreVendor --description '	ignores any _vendor directory.'
complete -c hugo-gen-doc -l ignoreVendorPaths --description '	ignores any _vendor for module paths matching the given Glob pattern.'
complete -c hugo-gen-doc -l log --description '	enable Logging.'
complete -c hugo-gen-doc -l logFile --description '	log File path (if set, logging enabled automatically).'
complete -c hugo-gen-doc -l quiet --description '	build in quiet mode.'
complete -c hugo-gen-doc -s s -l source --description '	filesystem path to read files relative from.'
complete -c hugo-gen-doc -l themesDir --description '	filesystem path to themes directory.'
complete -c hugo-gen-doc -s v -l verbose --description '	verbose output.'
complete -c hugo-gen-doc -l verboseLog --description '	verbose logging SEE ALSO.'

