# hugo-import-jekyll
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/hugo-import-jekyll.1.gz
complete -c hugo-import-jekyll -l force --description '	allow import into non-empty target directory.'
complete -c hugo-import-jekyll -s h -l help --description '	help for jekyll OPTIONS INHERITED FROM PARENT COMMANDS.'
complete -c hugo-import-jekyll -l config --description '	config file (default is path/config. yaml|json|toml).'
complete -c hugo-import-jekyll -l configDir --description '	config dir.'
complete -c hugo-import-jekyll -l debug --description '	debug output.'
complete -c hugo-import-jekyll -s e -l environment --description '	build environment.'
complete -c hugo-import-jekyll -l ignoreVendor --description '	ignores any _vendor directory.'
complete -c hugo-import-jekyll -l ignoreVendorPaths --description '	ignores any _vendor for module paths matching the given Glob pattern.'
complete -c hugo-import-jekyll -l log --description '	enable Logging.'
complete -c hugo-import-jekyll -l logFile --description '	log File path (if set, logging enabled automatically).'
complete -c hugo-import-jekyll -l quiet --description '	build in quiet mode.'
complete -c hugo-import-jekyll -s s -l source --description '	filesystem path to read files relative from.'
complete -c hugo-import-jekyll -l themesDir --description '	filesystem path to themes directory.'
complete -c hugo-import-jekyll -s v -l verbose --description '	verbose output.'
complete -c hugo-import-jekyll -l verboseLog --description '	verbose logging SEE ALSO.'

