# hugo-version
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/hugo-version.1.gz
complete -c hugo-version -s h -l help --description '	help for version OPTIONS INHERITED FROM PARENT COMMANDS.'
complete -c hugo-version -l config --description '	config file (default is path/config. yaml|json|toml).'
complete -c hugo-version -l configDir --description '	config dir.'
complete -c hugo-version -l debug --description '	debug output.'
complete -c hugo-version -s e -l environment --description '	build environment.'
complete -c hugo-version -l ignoreVendor --description '	ignores any _vendor directory.'
complete -c hugo-version -l ignoreVendorPaths --description '	ignores any _vendor for module paths matching the given Glob pattern.'
complete -c hugo-version -l log --description '	enable Logging.'
complete -c hugo-version -l logFile --description '	log File path (if set, logging enabled automatically).'
complete -c hugo-version -l quiet --description '	build in quiet mode.'
complete -c hugo-version -s s -l source --description '	filesystem path to read files relative from.'
complete -c hugo-version -l themesDir --description '	filesystem path to themes directory.'
complete -c hugo-version -s v -l verbose --description '	verbose output.'
complete -c hugo-version -l verboseLog --description '	verbose logging SEE ALSO.'

