# hugo-config-mounts
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/hugo-config-mounts.1.gz
complete -c hugo-config-mounts -s h -l help --description '	help for mounts OPTIONS INHERITED FROM PARENT COMMANDS.'
complete -c hugo-config-mounts -l config --description '	config file (default is path/config. yaml|json|toml).'
complete -c hugo-config-mounts -l configDir --description '	config dir.'
complete -c hugo-config-mounts -l debug --description '	debug output.'
complete -c hugo-config-mounts -s e -l environment --description '	build environment.'
complete -c hugo-config-mounts -l ignoreVendor --description '	ignores any _vendor directory.'
complete -c hugo-config-mounts -l ignoreVendorPaths --description '	ignores any _vendor for module paths matching the given Glob pattern.'
complete -c hugo-config-mounts -l log --description '	enable Logging.'
complete -c hugo-config-mounts -l logFile --description '	log File path (if set, logging enabled automatically).'
complete -c hugo-config-mounts -l quiet --description '	build in quiet mode.'
complete -c hugo-config-mounts -s s -l source --description '	filesystem path to read files relative from.'
complete -c hugo-config-mounts -l themesDir --description '	filesystem path to themes directory.'
complete -c hugo-config-mounts -s v -l verbose --description '	verbose output.'
complete -c hugo-config-mounts -l verboseLog --description '	verbose logging SEE ALSO.'

