# hugo-convert-toJSON
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/hugo-convert-toJSON.1.gz
complete -c hugo-convert-toJSON -s h -l help --description '	help for toJSON OPTIONS INHERITED FROM PARENT COMMANDS.'
complete -c hugo-convert-toJSON -l config --description '	config file (default is path/config. yaml|json|toml).'
complete -c hugo-convert-toJSON -l configDir --description '	config dir.'
complete -c hugo-convert-toJSON -l debug --description '	debug output.'
complete -c hugo-convert-toJSON -s e -l environment --description '	build environment.'
complete -c hugo-convert-toJSON -l ignoreVendor --description '	ignores any _vendor directory.'
complete -c hugo-convert-toJSON -l ignoreVendorPaths --description '	ignores any _vendor for module paths matching the given Glob pattern.'
complete -c hugo-convert-toJSON -l log --description '	enable Logging.'
complete -c hugo-convert-toJSON -l logFile --description '	log File path (if set, logging enabled automatically).'
complete -c hugo-convert-toJSON -s o -l output --description '	filesystem path to write files to.'
complete -c hugo-convert-toJSON -l quiet --description '	build in quiet mode.'
complete -c hugo-convert-toJSON -s s -l source --description '	filesystem path to read files relative from.'
complete -c hugo-convert-toJSON -l themesDir --description '	filesystem path to themes directory.'
complete -c hugo-convert-toJSON -l unsafe --description '	enable less safe operations, please backup first.'
complete -c hugo-convert-toJSON -s v -l verbose --description '	verbose output.'
complete -c hugo-convert-toJSON -l verboseLog --description '	verbose logging SEE ALSO.'

