# hugo-gen-autocomplete
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/hugo-gen-autocomplete.1.gz
complete -c hugo-gen-autocomplete -l completionfile --description '	autocompletion file.'
complete -c hugo-gen-autocomplete -s h -l help --description '	help for autocomplete.'
complete -c hugo-gen-autocomplete -l type --description '	autocompletion type (currently only bash supported) OPTIONS INHERITED FROM P…'
complete -c hugo-gen-autocomplete -l config --description '	config file (default is path/config. yaml|json|toml).'
complete -c hugo-gen-autocomplete -l configDir --description '	config dir.'
complete -c hugo-gen-autocomplete -l debug --description '	debug output.'
complete -c hugo-gen-autocomplete -s e -l environment --description '	build environment.'
complete -c hugo-gen-autocomplete -l ignoreVendor --description '	ignores any _vendor directory.'
complete -c hugo-gen-autocomplete -l ignoreVendorPaths --description '	ignores any _vendor for module paths matching the given Glob pattern.'
complete -c hugo-gen-autocomplete -l log --description '	enable Logging.'
complete -c hugo-gen-autocomplete -l logFile --description '	log File path (if set, logging enabled automatically).'
complete -c hugo-gen-autocomplete -l quiet --description '	build in quiet mode.'
complete -c hugo-gen-autocomplete -s s -l source --description '	filesystem path to read files relative from.'
complete -c hugo-gen-autocomplete -l themesDir --description '	filesystem path to themes directory.'
complete -c hugo-gen-autocomplete -s v -l verbose --description '	verbose output.'
complete -c hugo-gen-autocomplete -l verboseLog --description '	verbose logging SEE ALSO.'

