# hugo-mod-graph
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/hugo-mod-graph.1.gz
complete -c hugo-mod-graph -s h -l help --description '	help for graph OPTIONS INHERITED FROM PARENT COMMANDS.'
complete -c hugo-mod-graph -l config --description '	config file (default is path/config. yaml|json|toml).'
complete -c hugo-mod-graph -l configDir --description '	config dir.'
complete -c hugo-mod-graph -l debug --description '	debug output.'
complete -c hugo-mod-graph -s e -l environment --description '	build environment.'
complete -c hugo-mod-graph -l ignoreVendor --description '	ignores any _vendor directory.'
complete -c hugo-mod-graph -l ignoreVendorPaths --description '	ignores any _vendor for module paths matching the given Glob pattern.'
complete -c hugo-mod-graph -l log --description '	enable Logging.'
complete -c hugo-mod-graph -l logFile --description '	log File path (if set, logging enabled automatically).'
complete -c hugo-mod-graph -l quiet --description '	build in quiet mode.'
complete -c hugo-mod-graph -s s -l source --description '	filesystem path to read files relative from.'
complete -c hugo-mod-graph -l themesDir --description '	filesystem path to themes directory.'
complete -c hugo-mod-graph -s v -l verbose --description '	verbose output.'
complete -c hugo-mod-graph -l verboseLog --description '	verbose logging SEE ALSO.'

