# hugo-new-theme
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/hugo-new-theme.1.gz
complete -c hugo-new-theme -s h -l help --description '	help for theme OPTIONS INHERITED FROM PARENT COMMANDS.'
complete -c hugo-new-theme -l config --description '	config file (default is path/config. yaml|json|toml).'
complete -c hugo-new-theme -l configDir --description '	config dir.'
complete -c hugo-new-theme -l debug --description '	debug output.'
complete -c hugo-new-theme -s e -l environment --description '	build environment.'
complete -c hugo-new-theme -l ignoreVendor --description '	ignores any _vendor directory.'
complete -c hugo-new-theme -l ignoreVendorPaths --description '	ignores any _vendor for module paths matching the given Glob pattern.'
complete -c hugo-new-theme -l log --description '	enable Logging.'
complete -c hugo-new-theme -l logFile --description '	log File path (if set, logging enabled automatically).'
complete -c hugo-new-theme -l quiet --description '	build in quiet mode.'
complete -c hugo-new-theme -s s -l source --description '	filesystem path to read files relative from.'
complete -c hugo-new-theme -l themesDir --description '	filesystem path to themes directory.'
complete -c hugo-new-theme -s v -l verbose --description '	verbose output.'
complete -c hugo-new-theme -l verboseLog --description '	verbose logging SEE ALSO.'

