# imv
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/imv.1.gz
complete -c imv -l command --description 'Specify command to run instead of the default `mv\' or `cp\'.'
complete -c imv -l arg-options --description 'Specify what comma-separated options for mv, cp, or the command specified wit…'
complete -c imv -l pass-through --description 'Run mv/cp (or the command specified with --command) if two or more arguments …'
complete -c imv -l help --description 'Show summary of options.'
complete -c imv -l version --description 'Output version information and exit.'

