# ired
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/ired.1.gz
complete -c ired -s h --description 'Show help message.'
complete -c ired -s v --description 'Show version information.'
complete -c ired -s n --description 'Do not be verbose.'
complete -c ired -s i --description 'Interpret a script file as ired commands.'

