# iwpriv
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man8/iwpriv.8.gz
complete -c iwpriv -s a -l all --description 'Execute and display all the private commands that don\'t take any arguments (i.'

