# kpsestat
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/kpsestat.1.gz
complete -c kpsestat -l help --description 'Print help message and exit.'
complete -c kpsestat -l version --description 'Print version information and exit.'

