# mariadb-conv
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/mariadb-conv.1.gz
complete -c mariadb-conv -l from --description '.'
complete -c mariadb-conv -s f --description '.'
complete -c mariadb-conv -l to --description '.'
complete -c mariadb-conv -s t --description '.'
complete -c mariadb-conv -l continue --description '.'
complete -c mariadb-conv -s c --description '.'
complete -c mariadb-conv -l delimiter --description '.'

