# mark
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/mark.1.gz
complete -c mark -o add --description 'switch tells mark to add messages to sequences or to create a new sequence.'
complete -c mark -o sequence --description 'name argument (which must occur at least once) the messages named via msgs (w…'
complete -c mark -o zero --description 'switch is specified, the sequence will be emptied prior to adding the message…'
complete -c mark -o nozero --description 'means that each sequence should be appended to by the indicated messages.'
complete -c mark -o delete --description 'switch tells mark to delete messages from sequences, and is the dual of.'
complete -c mark -o public --description 'or.'
complete -c mark -o nopublic --description 'to force the new or modified sequences to be public or private.   The switch.'
complete -c mark -o list --description 'switch tells mark to list both the sequences defined for the folder and the m…'

