# mh-mkstemp
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/mh-mkstemp.1.gz
complete -c mh-mkstemp -o suffix --description 'switch is available and used, mkstemps (3).'
complete -c mh-mkstemp -o directory --description 'switch specifies a directory in which to create the file.'
complete -c mh-mkstemp -o prefix --description 'switch specifies an initial part, before the 6 characters, of the file name.'

