# mhfixmsg
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/mhfixmsg.1.gz
complete -c mhfixmsg -o decodetext --description 'switch enables a transformation to decode each base64 and quoted-printable te…'
complete -c mhfixmsg -o verbose --description 'is enabled).   Note that.'
complete -c mhfixmsg -o decodetypes --description 'switch specifies the message parts, by type and optionally subtype, to which.'
complete -c mhfixmsg -o crlflinebreaks --description 'switch selects this behavior and is enabled by default.   The.'
complete -c mhfixmsg -o nocrlflinebreaks --description 'switch causes carriage return characters to be stripped from, and not inserte…'
complete -c mhfixmsg -o textcharset --description 'switch specifies that all text/plain parts of the message(s) should be conver…'
complete -c mhfixmsg -o reformat --description 'switch.'
complete -c mhfixmsg -o replacetextplain --description 'switch broadens the applicability of.'
complete -c mhfixmsg -o fixboundary --description 'switch enables a transformation to repair the boundary portion of the Content…'
complete -c mhfixmsg -o fixcte --description 'switch enables a transformation to change the Content-Transfer-Encoding from …'
complete -c mhfixmsg -o fixtype --description 'switch ensures that each part of the message has the correct MIME type shown …'
complete -c mhfixmsg -o file --description 'file switch directs mhfixmsg to use the specified file as the source message,…'
complete -c mhfixmsg -o outfile --description 'switch is not enabled when using the standard input stream, mhfixmsg will not…'
complete -c mhfixmsg -o rmmproc --description 'switch may be used to override this profile component.   The.'
complete -c mhfixmsg -o normmproc --description 'switch disables the use of any rmmproc profile component and negates all prio…'
complete -c mhfixmsg -o nochangecur --description 'switch is enabled.   If the.'

