# mhical
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/mhical.1.gz
complete -c mhical -o format --description 'string and.'
complete -c mhical -o form --description 'formatfile switches may be used to specify a format string or a format file t…'
complete -c mhical -o reply --description 'switch generates a reply from the event request.'
complete -c mhical -o cancel --description 'switch generates an iCalendar event that can be used to cancel the event requ…'
complete -c mhical -o infile --description 'and.'
complete -c mhical -o outfile --description 'respectively, switches can be used to override these defaults.'
complete -c mhical -o contenttype --description 'switch instructs mhical to insert a Content-Type header at the beginning of i…'
complete -c mhical -o unfold --description 'switch echoes the event request, but with all lines unfolded.'
complete -c mhical -o debug --description 'switch reveals minute details of the parse process.'

