# mhl
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/mhl.1.gz
complete -c mhl -o bell --description 'option tells mhl to ring the terminal\'s bell at the end of each page, while t…'
complete -c mhl -o clear --description 'option tells mhl to clear the screen at the end of each page (or output a for…'
complete -c mhl -o moreproc --description 'program switch.'
complete -c mhl -o length --description 'length and.'
complete -c mhl -o width --description 'width switches set the screen length and width, respectively.'
complete -c mhl -o form --description 'formatfile switch.'
complete -c mhl -o folder --description '+folder switch sets the nmh folder name, which is used for the messagename: f…'
complete -c mhl -o header --description 'option to show .'
complete -c mhl -o fmtproc --description 'and.'
complete -c mhl -o nofmtproc --description 'switches can be used to override the formatproc profile entry.'

