# mhlist
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/mhlist.1.gz
complete -c mhlist -o headers --description 'switch indicates that a one-line banner should be displayed above the listing…'
complete -c mhlist -o realsize --description 'switch tells mhlist to evaluate the native (decoded) format of each content p…'
complete -c mhlist -o verbose --description 'switch is present, then the listing will show any extra information that is p…'
complete -c mhlist -o disposition --description 'switch is present, then the listing will show any relevant information from t…'
complete -c mhlist -o file --description 'file directs mhlist to use the specified file as the source message, rather t…'
complete -c mhlist -o part --description '.'
complete -c mhlist -o type --description 'and.'
complete -c mhlist -o prefer --description 'switches, you may limit and reorder the set of parts to be listed, based on p…'
complete -c mhlist -l '--	--------' --description 'text	plain, enriched multipart	mixed, alternative, digest, parallel message	r…'
complete -c mhlist -o noprefer --description 'switch will cancel any previous.'
complete -c mhlist -o check --description 'switch tells mhlist to check each content for an integrity checksum.'
complete -c mhlist -o nochangecur --description 'option is specified.'

