# mhlogin
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/mhlogin.1.gz
complete -c mhlogin -o user --description 'username.'
complete -c mhlogin -o saslmech --description '.'
complete -c mhlogin -o authservice --description 'gmail and load the printed URL in your browser.'
complete -c mhlogin -o browser --description 'switch causes mhlogin to load the URL directly into a new browser session.'
complete -c mhlogin -o snoop --description 'switch can be used to view the HTTP transaction.'
complete -c mhlogin -l 'new-window\'' --description 'The username should be a complete email address.'

