# mhmail
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/mhmail.1.gz
complete -c mhmail -o subject --description 'switch can be used to specify the Subject: field of the message.'
complete -c mhmail -o resent --description 'switch indicates that the message body is a fully formed message that will be…'
complete -c mhmail -o body --description 'text switch.'
complete -c mhmail -o cc --description 'switch is used, all addresses following it, even if there are intervening swi…'
complete -c mhmail -o to --description 'are placed in the cc: field.   The optional.'
complete -c mhmail -o from --description 'addr , you can specify the From: header of the draft.   If no.'
complete -c mhmail -o headerfield --description 'name:value switch adds a header field with the specified name and value to th…'
complete -c mhmail -o attach --description 'switch causes MIME-Version and Content-Type headers to be added to the messag…'
complete -c mhmail -o profile --description 'switch instructs mhmail to use send instead of post to send the message.'
complete -c mhmail -o nosend --description 'option shows the draft file that would be posted/sent on the command\'s standa…'
complete -c mhmail -o send --description 'provides the default behavior of posting or sending the message.'

