# mhparam
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/mhparam.1.gz
complete -c mhparam -o component --description 'is given, then the component name is displayed along with the profile compone…'
complete -c mhparam -o nocomponent --description '.'
complete -c mhparam -o all --description 'is specified, then all components in the nmh profile are displayed and other …'
complete -c mhparam -o debug --description 'switch displays all such other information available from mhparam .'

