# mhstore
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/mhstore.1.gz
complete -c mhstore -o part --description '.'
complete -c mhstore -o type --description 'and.'
complete -c mhstore -o prefer --description 'switches, you may limit and reorder the set of parts to be stored, based on p…'
complete -c mhstore -o file --description 'file switch directs mhstore to use the specified file as the source message, …'
complete -c mhstore -l '--	--------' --description 'text	plain, enriched multipart	mixed, alternative, digest, parallel message	r…'
complete -c mhstore -o noprefer --description 'switch will cancel any previous.'
complete -c mhstore -o check --description 'switch tells mhstore to check each content for an integrity checksum.'
complete -c mhstore -o outfile --description 'switch is given, its argument is used for the filename to store all of the co…'
complete -c mhstore -o auto --description 'switch is given, then mhstore will check if the message contains information …'
complete -c mhstore -o clobber --description 'switch setting other than the default of always to avoid overwriting existing…'
complete -c mhstore -o verbose --description 'switch directs mhstore to print out the names of files that it stores.'
complete -c mhstore -o noverbose --description 'switch suppresses these printouts.  Overwriting Existing Files The.'
complete -c mhstore -o rcache --description 'and.'
complete -c mhstore -o wcache --description 'switches, which define the policy for reading from, and writing to, the cache…'

