# mktexmf
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/mktexmf.1.gz
complete -c mktexmf -l help --description 'Print help message and exit.'
complete -c mktexmf -l version --description 'Print version information and exit.'

