# msgchk
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/msgchk.1.gz
complete -c msgchk -o notify --description 'type switch indicates under what circumstances msgchk should produce a messag…'
complete -c msgchk -o nonotify --description 'type switch has the inverted sense, so.'
complete -c msgchk -o date --description 'switch directs msgchk to print out the last date mail was read, if this can b…'
complete -c msgchk -o host --description 'hostname switch is given, msgchk will query this POP service host as to the s…'
complete -c msgchk -o user --description 'username switch.'
complete -c msgchk -o snoop --description 'which will allow you to watch the POP transaction take place between you and …'
complete -c msgchk -o sasl -o saslmech --description 'is used, the HTTP transaction is also shown.'
complete -c msgchk -o authservice --description 'service switch.'
complete -c msgchk -o initialtls --description 'switch will require the negotiation of TLS when connecting to the remote POP …'
complete -c msgchk -o notls --description 'switch will disable all attempts to negotiate TLS.'
complete -c msgchk -o certverify --description 'and.'
complete -c msgchk -o nocertverify --description 'switches.'

