# nethack
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man6/nethack.6.gz
complete -c nethack -o dec --description 'and.'
complete -c nethack -o ibm --description 'command line options are equivalent to the decgraphics and ibmgraphics run-ti…'
complete -c nethack -s u --description 'playername option supplies the answer to the question "Who are you?".'
complete -c nethack -s p --description 'profession option).'
complete -c nethack -s r --description 'race option).'
complete -c nethack -s s --description 'option alone will print out the list of your scores on the current version.'
complete -c nethack -s v --description 'reports on all versions present in the score file.  The.'
complete -c nethack -s n --description 'option suppresses printing of any news from the game administrator.'
complete -c nethack -s D --description 'or.'
complete -c nethack -s X --description 'option will start the game in a special non-scoring discovery mode.'
complete -c nethack -s d --description 'option, which must be the first argument if it appears, supplies a directory …'
complete -c nethack -l showpaths --description 'can be used to cause NetHack to show where it is expecting to find various co…'
complete -c nethack -l version --description 'can be used to cause NetHack to show the version information it was compiled …'
complete -c nethack -l version:paste --description 'can be used to cause NetHack to show the version information, then exit, whil…'

