# nsnake
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man6/nsnake.6.gz
complete -c nsnake -s h -l help --description 'Displays the quick help text.'
complete -c nsnake -s v -l version --description 'Displays the version and general information.'

