# nudoku
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man6/nudoku.6.gz
complete -c nudoku -s h --description 'Print help.'
complete -c nudoku -s v --description 'Display version information.'
complete -c nudoku -s c --description 'Do not use colors.  Black and white mode.'
complete -c nudoku -s d --description 'Choose difficulty.  Available options are: easy, normal, hard.'
complete -c nudoku -s s --description 'User provided stream.  The user can provide a sudoku himself.'
complete -c nudoku -s p --description 'Output PDF.  Prints a sudoku into a PDF file.  File name needs to follow.'
complete -c nudoku -s n --description 'Number of sudokuks to put in PDF.'
complete -c nudoku -s i --description 'Output PNG image.  Puts a single sudoku into an PNG image file.'

