# packf
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/packf.1.gz
complete -c packf -o mbox --description 'switch is given (the default), then the messages are separated using mbox (uu…'
complete -c packf -o mmdf --description 'switch is given, then the messages are separated by mmdf style delimiters.'
complete -c packf -o file --description 'name switch.'

