# pg_verifybackup
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/pg_verifybackup.1.gz
complete -c pg_verifybackup -o 'e
.br
--exit-on-error' --description 'Exit as soon as a problem with the backup is detected.'
complete -c pg_verifybackup -s i --description 'Ignore the specified file or directory, which should be expressed as a relati…'
complete -c pg_verifybackup -s m --description 'Use the manifest file at the specified path, rather than one located in the r…'
complete -c pg_verifybackup -o 'n
.br
--no-parse-wal' --description 'Don\\*(Aqt attempt to parse write-ahead log data that will be needed to recove…'
complete -c pg_verifybackup -o 'q
.br
--quiet' --description 'Don\\*(Aqt print anything when a backup is successfully verified.'
complete -c pg_verifybackup -o 's
.br
--skip-checksums' --description 'Do not verify data file checksums.'
complete -c pg_verifybackup -s w --description 'Try to parse WAL files stored in the specified directory, rather than in pg_w…'
complete -c pg_verifybackup -o 'V
.br
--version' --description 'Print the pg_verifybackup version and exit.'
complete -c pg_verifybackup -o '?
.br
--help' --description 'Show help about pg_verifybackup command line arguments, and exit.'
complete -c pg_verifybackup -l quiet --description 'flag will be used, so that pg_waldump will only report errors, without produc…'
complete -c pg_verifybackup -s e --description '.'
complete -c pg_verifybackup -l exit-on-error --description '.'
complete -c pg_verifybackup -l ignore --description '.'
complete -c pg_verifybackup -l manifest-path --description '.'
complete -c pg_verifybackup -s n --description '.'
complete -c pg_verifybackup -l no-parse-wal --description '.'
complete -c pg_verifybackup -s q --description '.'
complete -c pg_verifybackup -s s --description '.'
complete -c pg_verifybackup -l skip-checksums --description '.'
complete -c pg_verifybackup -l wal-directory --description '.'
complete -c pg_verifybackup -s V --description '.'
complete -c pg_verifybackup -l version --description '.'
complete -c pg_verifybackup -s '?' --description '.'
complete -c pg_verifybackup -l help --description '.'

