# prompter
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/prompter.1.gz
complete -c prompter -o editor --description 'prompter , or by the profile entry Editor: prompter, or when given the comman…'
complete -c prompter -l ------Enter --description 'or (if.'
complete -c prompter -o prepend --description 'was given).'
complete -c prompter -o doteof --description 'switch, a period on a line all by itself also signifies end-of-file.'
complete -c prompter -o rapid --description 'switch, if the draft already contains text in the message-body, it is not dis…'
complete -c prompter -o kill --description 'chr and.'
complete -c prompter -o erase --description 'chr , where chr may be a character; or `\\nnn\', where nnn is the octal value f…'
complete -c prompter -o noprepend --description 'is useful with comp.'
complete -c prompter -o use --description '.'

