# proot
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/proot.1.gz
complete -c proot -s r -l rootfs --description 'Use path as the new guest root file-system, default is /.'
complete -c proot -s b -l bind -s m -l mount --description 'Make the content of path accessible in the guest rootfs.'
complete -c proot -s q -l qemu --description 'Execute guest programs through QEMU as specified by command.'
complete -c proot -s w -l pwd -l cwd --description 'Set the initial working directory to path.'
complete -c proot -s v -l verbose --description 'Set the level of debug information to value.'
complete -c proot -s V -l version -l about --description 'Print version, copyright, license and contact, then exit.'
complete -c proot -s h -l help -l usage --description 'Print the version and the command-line usage, then exit.'
complete -c proot -s k -l kernel-release --description 'Make current kernel appear as kernel release string.'
complete -c proot -s 0 -l root-id --description 'Make current user appear as "root" and fake its privileges.'
complete -c proot -s i -l change-id --description 'Make current user and group appear as string "uid:gid".'
complete -c proot -s R --description 'Alias: -r *path* + a couple of recommended -b.'
complete -c proot -s S --description 'Alias: -0 -r *path* + a couple of recommended -b.'
complete -c proot -o rw-r--r-- --description 'proot -b ~/alternate_hosts:/etc/hosts.'

