# r2r
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/r2r.1.gz
complete -c r2r -s h --description 'Show the help/usage message.'
complete -c r2r -s n --description 'Do not run any test, just load/parse them.'
complete -c r2r -s q --description 'Quiet mode (use like this: r2r -qv).'
complete -c r2r -s v --description 'Show version number.'
complete -c r2r -s V --description 'Be verbose.'
complete -c r2r -s j --description 'Specify the number of tasks to run in parallel.'
complete -c r2r -s r --description 'Set path to radare2 executable.'
complete -c r2r -s m --description 'Set path to rasm2executable.'
complete -c r2r -s f --description 'Load the given binary when running the JSON tests.'
complete -c r2r -s C --description 'Early chdir before running any test El USAGE Pp Use the -n flag to dont run a…'

