# randpkt
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/randpkt.1.gz
complete -c randpkt -s b --description 'Default 5000.'
complete -c randpkt -s c --description 'Default 1000. Sp Defines the number of packets to generate.'

