# rcvpack
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/rcvpack.1.gz
complete -c rcvpack -o mbox --description 'switch is given (the default), messages are separated by mbox (uucp) style de…'
complete -c rcvpack -o mmdf --description 'switch is given, messages are separated by mmdf style delimiters, each messag…'

