# rcvstore
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/rcvstore.1.gz
complete -c rcvstore -o create --description 'is given (it is the default) and if the specified (or default) folder does no…'
complete -c rcvstore -o nocreate --description 'option.'
complete -c rcvstore -o unseen --description 'is given (it is on by default), and if the profile entry Unseen-Sequence is p…'
complete -c rcvstore -o nounseen --description 'to disable this.'
complete -c rcvstore -o sequence --description 'switch.   As with the commands pick and mark , you may also use the switches.'
complete -c rcvstore -o zero --description 'and.'
complete -c rcvstore -o nozero --description 'to specify whether to zero old sequences or not.  Similarly, use of the.'
complete -c rcvstore -o public --description 'and.'
complete -c rcvstore -o nopublic --description 'switches may be used to force these sequences to be public or private sequenc…'

