# rcvtty
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/rcvtty.1.gz
complete -c rcvtty -o form --description 'formatfile or.'
complete -c rcvtty -o format --description 'string option, similar to the equivalent options for scan and inc .'
complete -c rcvtty -o nonewline --description 'and.'
complete -c rcvtty -o nobell --description 'switches will inhibit these functions.'
complete -c rcvtty -o width --description 'columns may be given to specify the width of the scan line.'
complete -c rcvtty -o biff --description 'is given, then rcvtty will obey the notification status set by the command bi…'

