# refile
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/refile.1.gz
complete -c refile -o src --description '+folder .  If this is not given, the current folder is used by default.'
complete -c refile -o file --description 'file directs refile to use the specified file as the source message to be fil…'
complete -c refile -o link --description 'preserves the source folder copy of the message (i. e.'
complete -c refile -o nolink --description '(the default) deletes the filed messages from the source folder.'
complete -c refile -o preserve --description 'switch will override this message renaming, and try to preserve the number of…'
complete -c refile -o retainsequences --description 'adds it to those same sequences in the destination folder, creating any that …'
complete -c refile -o unlink --description 'switch (not to be confused with the.'
complete -c refile -o rmmproc --description 'program on the command line to override this profile specification.  The.'
complete -c refile -o normmproc --description 'option forces the message files to be deleted by renaming or unlinking them a…'
complete -c refile -o draft --description 'switch tells refile to file the <mh-dir>/draft.  FILES ^$HOME/.'

