# rmf
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/rmf.1.gz
complete -c rmf -o nointeractive --description 'option is given, then the folder will be removed without confirmation.'

