# rmm
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/rmm.1.gz
complete -c rmm -o unlink --description 'switch.  But messages removed by this method cannot be later recovered.'
complete -c rmm -o rmmproc --description 'switch may be used to override this profile component.   The.'
complete -c rmm -o normmproc --description 'switch disables the use of any rmmproc profile component and negates all prio…'

