# scan
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/scan.1.gz
complete -c scan -o annotate --description 'switch to the repl command).'
complete -c scan -o reverse --description 'makes scan list the messages in reverse order.'
complete -c scan -o file --description 'filename switch allows the user to obtain a scan listing of a mail drop file …'
complete -c scan -o width --description 'columns may be used to specify the width of the scan line.'
complete -c scan -o header --description 'switch produces a header line prior to the scan listing.'
complete -c scan -o clear --description 'switch is used and scan \'s output is directed to a terminal, then scan will c…'
complete -c scan -o format --description 'string or.'
complete -c scan -o form --description 'file switches are used.'

