# sendfiles
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/sendfiles.1.gz
complete -c sendfiles -o to --description 'switch specifies the recipient.   The.'
complete -c sendfiles -o subject --description 'switch specifies the subject.'
complete -c sendfiles -o from --description 'switch can, and should, be used to specify the sender\'s mailbox (name and ema…'
complete -c sendfiles -o compress --description 'command line switch can be used to override the run-time determination of the…'
complete -c sendfiles -o none --description 'disables compression.'
complete -c sendfiles -o delay --description 'switch specifies the number of seconds to pause in between postings, e. g.'
complete -c sendfiles -o 30 --description 'for example, is also supported.'
complete -c sendfiles -o auto --description 'switch, mhstore will automatically do the extraction for you: % mhlist 5-8  m…'

