# show
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/show.1.gz
complete -c show -o header --description 'and.'
complete -c show -o noheader --description 'are passed along to that program.'
complete -c show -o showproc --description 'program switch.   For example,.'
complete -c show -o showmimeproc --description 'program switch.'
complete -c show -o checkmime --description '(set by default) instructs show to test if any of the messages to be displaye…'
complete -c show -o nocheckmime --description 'disables this test and instructs show to use showproc , regardless of whether…'
complete -c show -o noshowproc --description 'switch will disable any formatting or paging of messages.'
complete -c show -o noconcat --description '.'

