# slocal
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/slocal.1.gz
complete -c slocal -o maildelivery --description 'file option.   The syntax of this file is specified below.'
complete -c slocal -o addr --description 'and.'
complete -c slocal -o sender --description 'switches.'
complete -c slocal -o file --description 'switch sets the name of the file from which the message should be read, inste…'
complete -c slocal -o user --description 'switch tells slocal the name of the user for whom it is delivering mail.'
complete -c slocal -o mailbox --description 'switch tells slocal the name of the user\'s mail drop file.'
complete -c slocal -o suppressdup --description 'slocal will keep a database containing the Message-ID\'s of incoming messages,…'
complete -c slocal -o info --description 'switch may be used to pass an arbitrary argument to sub-processes which sloca…'
complete -c slocal -o verbose --description 'switch causes slocal to give information on stdout about its progress.   The.'
complete -c slocal -o debug --description 'switch produces more verbose debugging output on stderr.'

