# sortm
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/sortm.1.gz
complete -c sortm -o noall --description 'switch is enabled, then sortm reports that as an error and exits with non-zer…'
complete -c sortm -o all --description 'switch can then be used on the command line to disable it.'
complete -c sortm -o verbose --description 'switch directs sortm to tell the user the general actions that it is taking t…'
complete -c sortm -o datefield --description 'field switch tells sortm the name of the field to use when making the date co…'
complete -c sortm -o textfield --description 'field switch causes sortm to sort messages by the specified text field.'
complete -c sortm -o limit --description 'days is specified, messages with the same textfields that are dated within `d…'
complete -c sortm -o nolimit --description 'makes the limit infinity.  With.'
complete -c sortm -o check --description 'switch, sortm inhibits all modifications to the folder if there are any such …'
complete -c sortm -o nocheck --description 'sortm sorts messages with a missing or invalid Date: field using their file m…'

