# texconfig
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/texconfig.1.gz
complete -c texconfig -s P --description 'option is given.'
complete -c texconfig -s O --description 'option in dvips(1).'

