# tftopl
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/tftopl.1.gz
complete -c tftopl -o charcode-format --description 'The argument  format specifies how character codes are output in the PL file.'
complete -c tftopl -o verbose --description 'Without this option, tftopl operates silently.'

