# vftovp
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/vftovp.1.gz
complete -c vftovp -o charcode-format --description 'The argument  format specifies how character codes are output in the VPL file.'
complete -c vftovp -o verbose --description 'Without this option, vftovp operates silently.'

