# weave
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/weave.1.gz
complete -c weave -s x --description 'says to omit the index, module name list, and table of contents pages.'

