# whatnow
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/whatnow.1.gz
complete -c whatnow -o noedit --description 'is given, in which case the initial edit is suppressed).'
complete -c whatnow -o push --description 'option).'
complete -c whatnow -o prompt --description 'string switch sets the prompting string for whatnow .'
complete -c whatnow -o draftfolder --description '+folder and.'
complete -c whatnow -o draftmessage --description 'msg switches invoke the nmh draft folder facility.'

