# whom
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/whom.1.gz
complete -c whom -o check --description 'is given).'
complete -c whom -o draftfolder --description '+folder and.'
complete -c whom -o draftmessage --description 'msg switches invoke the nmh draft folder facility.'
complete -c whom -o mts --description 'switch.'
complete -c whom -o server --description 'and the.'
complete -c whom -o port --description 'switches can be used to override the default mail server (defined by the /dat…'
complete -c whom -o snoop --description 'switch can be used to view the SMTP transaction.'
complete -c whom -o sasl --description 'switch will enable the use of SASL authentication with the SMTP MTA.'
complete -c whom -o saslmech --description 'switch can be used to select a particular SASL mechanism, and the.'
complete -c whom -o user --description 'switch can be used to select a authorization userid to provide to SASL other …'
complete -c whom -o tls --description '.'
complete -c whom -o initialtls --description 'and.'
complete -c whom -o notls --description 'switches will require and disable the negotiation of TLS support when connect…'
complete -c whom -o alias --description 'aliasfile switch will be read (more than one file, each preceded by.'

