# xkbcli-compile-keymap
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/xkbcli-compile-keymap.1.gz
complete -c xkbcli-compile-keymap -o '\\-help' --description 'Print help and exit.'
complete -c xkbcli-compile-keymap -o '\\-verbose' --description 'Enable verbose debugging output.'
complete -c xkbcli-compile-keymap -o '\\-rmlvo' --description 'Print the full RMLVO with the defaults filled in for missing elements.'
complete -c xkbcli-compile-keymap -o '\\-from\\-xkb' --description 'Load the XKB file from stdin, ignore RMLVO options.'
complete -c xkbcli-compile-keymap -o '\\-include' --description 'Add the given path to the include path list.'
complete -c xkbcli-compile-keymap -o '\\-include\\-defaults' --description 'Add the default set of include directories.'
complete -c xkbcli-compile-keymap -o '\\-rules' --description 'The XKB ruleset.'
complete -c xkbcli-compile-keymap -o '\\-model' --description 'The XKB model.'
complete -c xkbcli-compile-keymap -o '\\-layout' --description 'The XKB layout.'
complete -c xkbcli-compile-keymap -o '\\-variant' --description 'The XKB layout variant.'
complete -c xkbcli-compile-keymap -o '\\-options' --description 'The XKB options El SEE ALSO xkbcli 1, https://xkbcommon.'

