# xkbcli
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/xkbcli.1.gz
complete -c xkbcli -o '\\-help' --description 'Print help and exit.'
complete -c xkbcli -o '\\-version' --description 'Print the version and exit El COMMANDS -tag -width Ds how\\-to\\-type Show how …'

