# xkbcli-interactive-evdev
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/xkbcli-interactive-evdev.1.gz
complete -c xkbcli-interactive-evdev -o '\\-help' --description 'Print help and exit.'
complete -c xkbcli-interactive-evdev -o '\\-rules' --description 'The XKB ruleset.'
complete -c xkbcli-interactive-evdev -o '\\-model' --description 'The XKB model.'
complete -c xkbcli-interactive-evdev -o '\\-layout' --description 'The XKB layout.'
complete -c xkbcli-interactive-evdev -o '\\-variant' --description 'The XKB layout variant.'
complete -c xkbcli-interactive-evdev -o '\\-option' --description 'The XKB options.'
complete -c xkbcli-interactive-evdev -o '\\-keymap' --description 'Specify a keymap path.'
complete -c xkbcli-interactive-evdev -o '\\-report\\-state\\-changes' --description 'Report changes to the keyboard state.'
complete -c xkbcli-interactive-evdev -o '\\-enable\\-compose' --description 'Enable Compose functionality.'
complete -c xkbcli-interactive-evdev -o '\\-consumed\\-mode' --description 'Set the consumed modifiers mode (default: xkb).'
complete -c xkbcli-interactive-evdev -o '\\-without\\-x11\\-offset' --description 'Don\'t add an offset of 8 when converting an evdev keycode to an XKB keycode.'

