# xkbcli-list
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/xkbcli-list.1.gz
complete -c xkbcli-list -o '\\-help' --description 'Print help and exit.'
complete -c xkbcli-list -o '\\-verbose' --description 'Increase verbosity, use multiple times for debugging output.'
complete -c xkbcli-list -o '\\-ruleset' --description 'Load the ruleset with the given name.'
complete -c xkbcli-list -o '\\-skip\\-default\\-paths' --description 'Do not load the default XKB include paths.'
complete -c xkbcli-list -o '\\-load\\-exotic' --description 'Load exotic (extra) layouts El SEE ALSO xkbcli 1, https://xkbcommon.'

