# xkbcli-how-to-type
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/xkbcli-how-to-type.1.gz
complete -c xkbcli-how-to-type -o '\\-rules' --description 'The XKB ruleset.'
complete -c xkbcli-how-to-type -o '\\-model' --description 'The XKB model.'
complete -c xkbcli-how-to-type -o '\\-layout' --description 'The XKB layout.'
complete -c xkbcli-how-to-type -o '\\-variant' --description 'The XKB layout variant.'
complete -c xkbcli-how-to-type -o '\\-options' --description 'The XKB options El SEE ALSO xkbcli 1, https://xkbcommon.'

